### ISSUE TITLE
[Usage]: Moving from 1 to 2 GPU's in vLLM

### ISSUE THREAD

**Issue by samuel-sujith** [vllm-project/vllm#10826]
### Your current environment

```text
k8s 1.31 using vllm-openai:latest
```

### How would you like to use vllm

I am currently running the QWEN model with 1 GPU with the below manifest

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: q2q-7b
  namespace: nmlp
  labels:
    app: q2q-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q2q-7b
  template:
    metadata:
      labels:
        app: q2q-7b
    spec:
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: q2q-7b
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      runtimeClassName: nvidia
      containers:
      - name: q2q-7b
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve Qwen/QwQ-32B-Preview --gpu-memory-utilization 0.9 --max_model_len 13680"
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "10"
            memory: 100G
            nvidia.com/gpu: "1"
          requests:
            cpu: "10"
            memory: 100G
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
```

This works perfectly.

The trouble starts when i try to use 2 GPU's by changing the nvidia.com/gpu to 2.

The model does not load and the pod logs just dont progress.

Could you please help me with this.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
