### ISSUE TITLE
[New Model]: unsloth/Llama-3.3-70B-Instruct-bnb-4bit

### ISSUE THREAD

**Issue by Hyfred** [vllm-project/vllm#11725]
### The model to consider.

https://huggingface.co/unsloth/Llama-3.3-70B-Instruct-bnb-4bit

### The closest model vllm already supports.

not sure the closet one. 

### What's your difficulty of supporting the model you want?

unsloth based is inference faster.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
> unsloth based is inference faster.

could you plz provibe more details such as test scripts, your env and test results

**Comment by bbrala** [comment]
We have it running successfully on a l40s (using kubai)

```
spec:
  args:
    - '--max-model-len=8192'
    - '--max-num-batched-token=8192'
    - '--gpu-memory-utilization=0.99'
    - '--enforce-eager'
    - '--disable-log-requests'
    - '--max-num-seqs=16'
    - '--quantization=bitsandbytes'
    - '--load-format=bitsandbytes'
  engine: VLLM
  features:
    - TextGeneration
  maxReplicas: 1
  minReplicas: 1
  owner: ''
  replicas: 1
  resourceProfile: 'nvidia-gpu-l4:1'
  scaleDownDelaySeconds: 30
  targetRequests: 100
  url: 'hf://unsloth/Llama-3.3-70B-Instruct-bnb-4bit'
```
