### ISSUE TITLE
[Bug]: PaliGemma2 not working with OpenAI Docker serve

### ISSUE THREAD

**Issue by IngLP** [vllm-project/vllm#12052]
### Your current environment

Just using Docker image 0.6.6post1

### 🐛 Describe the bug

Just try to run https://huggingface.co/google/paligemma2-3b-pt-896 using Docker vllm image. My docker compose follows:

```
services:
  app:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=hf_
    ipc: host
    command:
      - --host
      - 0.0.0.0
      - --model
      - google/paligemma2-3b-pt-896
      - --limit-mm-per-prompt
      - 'image=1'
      - --trust-remote-code
      - --max-model-len
      - "8192"

```

It does NOT work, the issue is the same reported in the pull request here: https://github.com/vllm-project/vllm/pull/11142#issuecomment-2541342321
and is:
`ValueError: As of transformers v4.44, default chat template is no longer allowed, so you must provide a chat template if the tokenizer does not define one.`

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
