### ISSUE TITLE
[Usage]: vLLM seems to not support Flash Attention 3 with kv cache dtype 'fp8'

### ISSUE THREAD

**Issue by jorgeantonio21** [vllm-project/vllm#12543]
### Your current environment

I am running a vLLM instance to serve DeepSeek R1 on a 8xH200 node, using docker compose, whose service is defined as:

```yaml
vllm:
    <<: *inference-service-cuda
    container_name: chat-completions
    profiles: [chat_completions_vllm]
    image: vllm/vllm-openai:v0.7.0
    environment:
    # Backend for attention computation
    # Available options:
    # - "TORCH_SDPA": use torch.nn.MultiheadAttention
    # - "FLASH_ATTN": use FlashAttention
    # - "XFORMERS": use XFormers
    # - "ROCM_FLASH": use ROCmFlashAttention
    # - "FLASHINFER": use flashinfer (recommended for fp8 quantized models)
      - VLLM_ATTENTION_BACKEND=FLASH_ATTN
      - VLLM_FLASH_ATTN_VERSION=3
    ipc: host
    command: ${DEEPSEEK_VLLM_ENGINE_ARGS}
````

where I specify both `FLASH_ATTN` backend with version `3`. The vLLM engine args is specified to run with `--kv-cache-dtype fp8`. Unfortunately, it seems the current logic does not allow running the model with flash attention backend, even if the version is 3. Here are the logs:

```
ds-chat-completions  | INFO 01-29 01:53:21 cuda.py:185] Cannot use FlashAttention-2 backend for FP8 KV cache.
ds-chat-completions  | WARNING 01-29 01:53:21 cuda.py:187] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
ds-chat-completions  | INFO 01-29 01:53:21 cuda.py:222] Using XFormers backend.
ds-chat-completions  | (VllmWorkerProcess pid=349) INFO 01-29 01:53:21 cuda.py:185] Cannot use FlashAttention-2 backend for FP8 KV cache.
ds-chat-completions  | (VllmWorkerProcess pid=349) WARNING 01-29 01:53:21 cuda.py:187] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
ds-chat-completions  | (VllmWorkerProcess pid=349) INFO 01-29 01:53:21 cuda.py:222] Using XFormers backend.
ds-chat-completions  | (VllmWorkerProcess pid=354) INFO 01-29 01:53:21 cuda.py:185] Cannot use FlashAttention-2 backend for FP8 KV cache.
ds-chat-completions  | (VllmWorkerProcess pid=354) WARNING 01-29 01:53:21 cuda.py:187] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
ds-chat-completions  | (VllmWorkerProcess pid=354) INFO 01-29 01:53:21 cuda.py:222] Using XFormers backend.
ds-chat-completions  | (VllmWorkerProcess pid=353) INFO 01-29 01:53:21 cuda.py:185] Cannot use FlashAttention-2 backend for FP8 KV cache.
ds-chat-completions  | (VllmWorkerProcess pid=353) WARNING 01-29 01:53:21 cuda.py:187] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
ds-chat-completions  | (VllmWorkerProcess pid=353) INFO 01-29 01:53:21 cuda.py:222] Using XFormers backend.
ds-chat-completions  | (VllmWorkerProcess pid=350) INFO 01-29 01:53:21 cuda.py:185] Cannot use FlashAttention-2 backend for FP8 KV cache.
ds-chat-completions  | (VllmWorkerProcess pid=350) WARNING 01-29 01:53:21 cuda.py:187] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
ds-chat-completions  | (VllmWorkerProcess pid=351) INFO 01-29 01:53:21 cuda.py:185] Cannot use FlashAttention-2 backend for FP8 KV cache.
ds-chat-completions  | (VllmWorkerProcess pid=350) INFO 01-29 01:53:21 cuda.py:222] Using XFormers backend.
ds-chat-completions  | (VllmWorkerProcess pid=351) WARNING 01-29 01:53:21 cuda.py:187] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
ds-chat-completions  | (VllmWorkerProcess pid=351) INFO 01-29 01:53:21 cuda.py:222] Using XFormers backend.
ds-chat-completions  | (VllmWorkerProcess pid=355) INFO 01-29 01:53:21 cuda.py:185] Cannot use FlashAttention-2 backend for FP8 KV cache.
ds-chat-completions  | (VllmWorkerProcess pid=355) WARNING 01-29 01:53:21 cuda.py:187] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
ds-chat-completions  | (VllmWorkerProcess pid=352) INFO 01-29 01:53:21 cuda.py:185] Cannot use FlashAttention-2 backend for FP8 KV cache.
ds-chat-completions  | (VllmWorkerProcess pid=355) INFO 01-29 01:53:21 cuda.py:222] Using XFormers backend.
ds-chat-completions  | (VllmWorkerProcess pid=352) WARNING 01-29 01:53:21 cuda.py:187] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
ds-chat-completions  | (VllmWorkerProcess pid=352) INFO 01-29 01:53:21 cuda.py:222] Using XFormers backend.
```

From what I understand, Flash Attention 3 supports fp8 quantization (at least per Dao's official repo). I further looked into the code and it is not clear how the vLLM forked flash attention is handling the method `is_fa_version_supported` is defined (which sets the backend to `XFormers` in case we specify the kv cache dtype to fp8).

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
