### ISSUE TITLE
[Bug]: 0.7.2 Docker Container doesn't support Qwen VL 2.5 Instruct yet?

### ISSUE THREAD

**Issue by andrePankraz** [vllm-project/vllm#12980]
### Your current environment

Docker-based.

### 🐛 Describe the bug

I start Docker VLLM Container like this:

```yaml
services:
  vllm-qwen25-vl-72b:
    image: vllm/vllm-openai:v0.7.2
    container_name: vllm-qwen25-vl-72b
    environment:
      - VLLM_NO_USAGE_STATS=1
      - VLLM_USE_V1=1
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3']
              capabilities: [ gpu ]
    network_mode: host
    volumes:
      - /mnt/sda/huggingface:/root/.cache/huggingface
      - .:/opt/vllm
    command:
      - --port=8003
      - --model=Qwen/Qwen2.5-VL-72B-Instruct
      - --tensor-parallel-size=4
      - --limit-mm-per-prompt=image=2
      - --disable-log-requests
      - --swap-space=5
    restart: unless-stopped
```

I get this as result:
```bash
$ docker compose up
[+] Running 1/0
 ✔ Container vllm-qwen25-vl-72b  Created                                                                                                                                                                     0.0s
Attaching to vllm-qwen25-vl-72b
vllm-qwen25-vl-72b  | INFO 02-08 23:47:57 __init__.py:190] Automatically detected platform cuda.
vllm-qwen25-vl-72b  | INFO 02-08 23:47:59 api_server.py:840] vLLM API server version 0.7.2
vllm-qwen25-vl-72b  | INFO 02-08 23:47:59 api_server.py:841] args: Namespace(host=None, port=8013, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, enable_reasoning=False, reasoning_parser=None, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen2.5-VL-72B-Instruct', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=None, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=5.0, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt={'image': 2}, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, disable_log_requests=True, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False)
vllm-qwen25-vl-72b  | WARNING 02-08 23:47:59 arg_utils.py:1326] Setting max_num_batched_tokens to 2048 for OPENAI_API_SERVER usage context.
vllm-qwen25-vl-72b  | Traceback (most recent call last):
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/transformers/models/auto/configuration_auto.py", line 1071, in from_pretrained
vllm-qwen25-vl-72b  |     config_class = CONFIG_MAPPING[config_dict["model_type"]]
vllm-qwen25-vl-72b  |                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/transformers/models/auto/configuration_auto.py", line 773, in __getitem__
vllm-qwen25-vl-72b  |     raise KeyError(key)
vllm-qwen25-vl-72b  | KeyError: 'qwen2_5_vl'
vllm-qwen25-vl-72b  |
vllm-qwen25-vl-72b  | During handling of the above exception, another exception occurred:
vllm-qwen25-vl-72b  |
vllm-qwen25-vl-72b  | Traceback (most recent call last):
vllm-qwen25-vl-72b  |   File "<frozen runpy>", line 198, in _run_module_as_main
vllm-qwen25-vl-72b  |   File "<frozen runpy>", line 88, in _run_code
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 911, in <module>
vllm-qwen25-vl-72b  |     uvloop.run(run_server(args))
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
vllm-qwen25-vl-72b  |     return __asyncio.run(
vllm-qwen25-vl-72b  |            ^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
vllm-qwen25-vl-72b  |     return runner.run(main)
vllm-qwen25-vl-72b  |            ^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
vllm-qwen25-vl-72b  |     return self._loop.run_until_complete(task)
vllm-qwen25-vl-72b  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
vllm-qwen25-vl-72b  |     return await main
vllm-qwen25-vl-72b  |            ^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 875, in run_server
vllm-qwen25-vl-72b  |     async with build_async_engine_client(args) as engine_client:
vllm-qwen25-vl-72b  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
vllm-qwen25-vl-72b  |     return await anext(self.gen)
vllm-qwen25-vl-72b  |            ^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 136, in build_async_engine_client
vllm-qwen25-vl-72b  |     async with build_async_engine_client_from_engine_args(
vllm-qwen25-vl-72b  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
vllm-qwen25-vl-72b  |     return await anext(self.gen)
vllm-qwen25-vl-72b  |            ^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 160, in build_async_engine_client_from_engine_args
vllm-qwen25-vl-72b  |     engine_client = AsyncLLMEngine.from_engine_args(
vllm-qwen25-vl-72b  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 104, in from_engine_args
vllm-qwen25-vl-72b  |     vllm_config = engine_args.create_engine_config(usage_context)
vllm-qwen25-vl-72b  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 1075, in create_engine_config
vllm-qwen25-vl-72b  |     model_config = self.create_model_config()
vllm-qwen25-vl-72b  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 998, in create_model_config
vllm-qwen25-vl-72b  |     return ModelConfig(
vllm-qwen25-vl-72b  |            ^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/config.py", line 302, in __init__
vllm-qwen25-vl-72b  |     hf_config = get_config(self.model, trust_remote_code, revision,
vllm-qwen25-vl-72b  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/config.py", line 245, in get_config
vllm-qwen25-vl-72b  |     raise e
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/config.py", line 225, in get_config
vllm-qwen25-vl-72b  |     config = AutoConfig.from_pretrained(
vllm-qwen25-vl-72b  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-qwen25-vl-72b  |   File "/usr/local/lib/python3.12/dist-packages/transformers/models/auto/configuration_auto.py", line 1073, in from_pretrained
vllm-qwen25-vl-72b  |     raise ValueError(
vllm-qwen25-vl-72b  | ValueError: The checkpoint you are trying to load has model type `qwen2_5_vl` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
vllm-qwen25-vl-72b  |
vllm-qwen25-vl-72b  | You can update Transformers with the command `pip install --upgrade transformers`. If this does not work, and the checkpoint is very new, then there may not be a release version that supports this model yet. In this case, you can get the most up-to-date code by installing Transformers from source with the command `pip install git+https://github.com/huggingface/transformers.git`
vllm-qwen25-vl-72b exited with code 1
```

Wasn't 0.7.2 supposed to support Qwen 2.5 VL as a main feature?
Am i doing something wrong?

I even updated transformer in container - didn't help.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by MustafaHek** [comment]
Did you update transformers from the git repo?:

`pip install git+https://github.com/huggingface/transformers.git`

The model is quite new and the release on pip is does not support it yet.

**Comment by andrePankraz** [comment]
Yes thats true, it can download model now with this changes setup:

```bash
# Use the base vLLM image
FROM vllm/vllm-openai:v0.7.2

ARG ARTIFACTORY_USER
ARG ARTIFACTORY_TOKEN

# Set the internal PyPI mirror (Artifactory) URL using the provided credentials.
ENV PIP_INDEX_URL="https://${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN}@artifacts..../artifactory/api/pypi/initai-platform-pypi/simple"

# Set proxy environment variables as required
ENV HTTPS_PROXY=http://proxy...
ENV HTTP_PROXY=http://proxy...

# Install the latest Transformers directly from GitHub,
# ensuring that pip uses your internal index for dependency resolution.
RUN pip install --upgrade --index-url ${PIP_INDEX_URL} git+https://github.com/huggingface/transformers.git
```


```yaml
services:
  vllm-qwen25-vl-72b:
    # image: vllm/vllm-openai:v0.7.2
    build:
      context: .
      args:
        ARTIFACTORY_USER: ${ARTIFACTORY_USER}
        ARTIFACTORY_TOKEN: ${ARTIFACTORY_TOKEN}
    container_name: vllm-qwen25-vl-72b
    environment:
      - HTTPS_PROXY=http://proxy....
      - HTTP_PROXY=http://proxy....
      - NO_PROXY=10.9....
      - HF_TOKEN=$HF_TOKEN
      - VLLM_NO_USAGE_STATS=1
      - VLLM_USE_V1=1
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3']
              capabilities: [ gpu ]
    network_mode: host
    volumes:
      - /mnt/sda/huggingface:/root/.cache/huggingface
      - .:/opt/vllm
    command:
      - --port=8013
      - --model=Qwen/Qwen2.5-VL-72B-Instruct
      - --served-model-name=Qwen/Qwen2-VL-7B-Instruct
      - --max-model-len=16384
      - --tensor-parallel-size=4
      - --limit-mm-per-prompt=image=1
      - --disable-log-requests
      - --swap-space=5
    restart: unless-stopped
```

Will check how it works.

I still think, vllm is only than model-XY-ready (on twitter and all that), if the vLLM-Docker container also supports the model out of the box.
