### ISSUE TITLE
[Bug]: meta-llama/Llama-3.2-90B-Vision-Instruct in vllm/vllm-openai:latest

### ISSUE THREAD

**Issue by nrepesh** [vllm-project/vllm#13307]
### Your current environment

<details>
vllm/vllm-openai:latest docker image 
or 
[v0.7.2](https://hub.docker.com/layers/vllm/vllm-openai/v0.7.2/images/sha256-65009b48651a8bc216ab57ed64d7c3d0b0ee8cec77674ccdbcb5f0e8362793a1)

</details>

### 🐛 Describe the bug

```
version: '3.8'

services:
  vllm-vllama-api:
    image: vllm/vllm-openai:latest
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - ./vllm-llama3.2:/root/.cache/huggingface
    command: [ "--model", "meta-llama/Llama-3.2-90B-Vision-Instruct", "--enforce-eager", "--tensor-parallel-size", "2", "--max-num-seqs", "16", "--trust-remote-code" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '5', '6' ]
```

Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 989, in from_pretrained
config_class = CONFIG_MAPPING[config_dict["model_type"]]
File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 691, in __getitem__
     raise KeyError(key)
 KeyError: 'mllama'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
     exec(code, run_globals)
   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 317, in <module>
     run_server(args)
   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 231, in run_server
     if llm_engine is not None else AsyncLLMEngine.from_engine_args(
   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 457, in from_engine_args
     engine_config = engine_args.create_engine_config()
   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 699, in create_engine_config
     model_config = ModelConfig(
   File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 152, in __init__
     self.hf_config = get_config(self.model, trust_remote_code, revision,
   File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/config.py", line 59, in get_config
     raise e
   File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/config.py", line 44, in get_config
     config = AutoConfig.from_pretrained(
   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 991, in from_pretrained
     raise ValueError(
 ValueError: The checkpoint you are trying to load has model type `mllama` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

Is the reason that the vllm/vllm-openai:latest version of the docker does not support meta-llama/Llama-3.2-90B-Vision-Instruct?

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
