### ISSUE TITLE
[Bug]: "ImportError: Please install vllm[audio] for audio support" while running whisper with '--task=transcription'

### ISSUE THREAD

**Issue by IanZhengruShen** [vllm-project/vllm#13675]
### Your current environment

I'm using the latest docker image vllm/vllm-openai:latest

### 🐛 Describe the bug

I set up the vllm using docker, my docker-compose file:
````
services:
  vllm-openai-whisper:
    image: 'vllm/vllm-openai:latest'
    volumes:
      - '/xxxx/.cache/huggingface:/root/.cache/huggingface'
    command:
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--api-key=xxxx"
      - "--model=openai/whisper-large-v3-turbo"
      - "--task=transcription"
````
I'm able to set up the container without any issue, but when I'm trying to send requests to '/v1/audio/transcriptions', I got the following import error: 

ImportError: Please install vllm[audio] for audio support

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
