### ISSUE TITLE
[Doc]: header of compatibility_matrix overlaps

### ISSUE THREAD

**Issue by vie-serendipity** [vllm-project/vllm#13749]
### 📚 The doc issue

I found headers of compatibility_matrix overlap. It seems `vertical-table-header` css has some problems.
[compatibility_matrix](https://docs.vllm.ai/en/latest/features/compatibility_matrix.html)
I test the following css and it works fine. If needed, I'd like to submit a pr to fix it.

### Suggest a potential alternative/fix

```css
.vertical-table-header th.head:not(.stub) {
    writing-mode: sideways-lr;
    white-space: nowrap;
    p {
       margin: 0;
    }
}

.vertical-table-header th abbr {
    white-space: nowrap;
}
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
