### ISSUE TITLE
[Bug]:  Error when Run Image Docker Vllm v0.7.3 -  Unexpected error from cudaGetDeviceCount().  ....

### ISSUE THREAD

**Issue by duytran1999** [vllm-project/vllm#14403]
### Your current environment

<details>
<summary>

I have problem when start docker image  with vllm v0.7.3 ( lasted now ) 

![Image](https://github.com/user-attachments/assets/5bc4ee89-474c-494f-8f1a-39c61422a8ce)

My docker-compose.yml file
### Docker Compose Configuration

```yaml
version: "3.8"
services:
    vllm-openai:
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
        environment:
            - HUGGING_FACE_HUB_TOKEN=<...>
        ports:
            - 8000:8000
        ipc: host
        image: vllm/vllm-openai:latest 
        runtime: nvidia
        command: --model deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
```
this my result when  run nvidia-smi

![Image](https://github.com/user-attachments/assets/02e8d8d4-e38f-41e8-9160-af31a9cf8445)

and nvcc --version

![Image](https://github.com/user-attachments/assets/16cf6a9d-746f-4356-ab0d-278df85de43f)

</summary>

</details>

### 🐛 Describe the bug

![Image](https://github.com/user-attachments/assets/d09ea20e-d3ae-49a9-8f47-3a3fe7b91d6c)

### Before submitting a new issue...

- [ ] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
