### ISSUE TITLE
[Bug]: Qwen VL 2.5 doesn't work in v0.8.0 - again

### ISSUE THREAD

**Issue by andrePankraz** [vllm-project/vllm#15122]
### Your current environment

Official docker container v0.8.0 from https://hub.docker.com/r/vllm/vllm-openai/tags

Setup with something like

```
services:
  vllm-qwen25-vl-72b:
    image: vllm/vllm-openai:v0.8.0
    container_name: vllm-qwen25-vl-72b
    environment:
      - HF_TOKEN=$HF_TOKEN
      - VLLM_NO_USAGE_STATS=1
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3']
              capabilities: [ gpu ]
    network_mode: host
    volumes:
      - /mnt/sda/huggingface:/root/.cache/huggingface
      - .:/opt/vllm
    command:
      - --port=8003
      - --model=Qwen/Qwen2.5-VL-72B-Instruct
      - --tensor-parallel-size=4
      - --limit-mm-per-prompt=image=2
      - --disable-log-requests
      - --gpu-memory-utilization=0.90
      - --swap-space=5
    restart: unless-stopped
```

### 🐛 Describe the bug

The images are all totally wrong or partially wrong. Example call:

```
curl 'https://ai1.dev.init/llm-vision/v1/chat/completions' -k -H 'Content-Type: application/json' -d @- <<EOF
{
    "model": "Qwen/Qwen2.5-VL-72B-Instruct",
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "data:image/avif;base64,$(curl -s https://aomediacodec.github.io/av1-avif/testFiles/Link-U/hato.jpg | base64 -w 0)"
                    }
                },
                {
                    "type": "text",
                    "text": "Describe image"
                }
            ]
        }
    ],
    "skip_special_tokens": false
}
EOF
```

Result:

```
{"id":"chatcmpl-5e74576b1fb64899a05658b15968a549","object":"chat.completion","created":1742382493,"model":"Qwen/Qwen2-VL-7B-Instruct","choices":[{"index":0,"message":{"role":"assistant","reasoning_content":null,"content":"The image appears to be a highly distorted and fragmented collage of various scenes, possibly from a video or a series of photographs. The distortion creates a kaleidoscopic effect with overlapping and repeating patterns. The colors are muted and earthy, with shades of green, brown, yellow, and gray dominating the palette.\n\nThe fragments seem to depict outdoor scenes, possibly including elements like grass, trees, and parts of buildings or structures. The overall effect is abstract and chaotic, making it difficult to discern specific details or objects within the image. The distortion and repetition give the image a surreal and dreamlike quality.","tool_calls":[]},"logprobs":null,"finish_reason":"stop","stop_reason":null}],"usage":{"prompt_tokens":8053,"total_tokens":8175,"completion_tokens":122,"prompt_tokens_details":null},"prompt_logprobs":null}
```

Former models recognized some obiligatory doves in the image (with varying other background stuff). But here the model just seems to sees scrambled stuff.

I also have this issues with many many other images. The recognition quality gets worse than models from 2 years ago with Qwen VL 2.5 72, which is normally very very good. Something is wrong.

Do you have small automatic tests/benchmarks for some base models, if you make sweeping arch/design changes and very commonly used models don't run over multiple versions? If I remember for Qwen VL: We now had multiple iterations with too strict token-mm-limit-calculation, we hat problems with old transformer lib in docker, we had problem with incompatible python - now that. It's an unusable mess.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
