### ISSUE TITLE
[Usage]:Phi-4-multimodal-instruct

### ISSUE THREAD

**Issue by MemmoB** [vllm-project/vllm#15468]
### Your current environment

I'm using vllm in kubernetes, docker image version 0.8.1.
I'm having a hard time getting LoRAs to load although I can see that the path is availble inside the running Pod.
My deployment yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi-4-multimodal-instruct
labels:
    app: phi-4-multimodal-instruct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phi-4-multimodal-instruct
  template:
    metadata:
      labels:
        app: phi-4-multimodal-instruct
    spec:
      volumes:
      - name: model-cache
        hostPath:
          path: /mnt/data
          type: Directory
      # vLLM needs to access the host's shared memory for tensor parallel inference.
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: phi-4-multimodal-instruct
        image: vllm/vllm-openai:v0.8.1
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve microsoft/Phi-4-multimodal-instruct --trust-remote-code --port 8000 --enforce-eager --gpu-memory-utilization 0.8  --dtype auto --max-model-len 128000 --enable-lora --max-lora-rank 320 --lora-extra-vocab-size 512 --limit-mm-per-prompt audio=3,image=3 --max-loras 2"
        ]
        env:
          - name: VLLM_ALLOW_RUNTIME_LORA_UPDATING
            value: "True"

        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "10"
            memory: "128Gi"
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: "64Gi"
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: model-cache
        - name: shm
          mountPath: /dev/shm
```
I have tried both loading dynamically and using the `speech=<path of speech-lora>` but both fail with the same  `Adapter not found ` error.
I can ssh into the pod and I can verify that the folder is on the correct path:
`/root/.cache/huggingface/hub/models--microsoft--Phi-4-multimodal-instruct/snapshots/6cf9696e152090d43282b3830adbb6cc8b2d0250/speech-lora`

```
 curl -X POST http://localhost:8000/v1/load_lora_adapter \
-H "Content-Type: application/json" \
-d '{"lora_name": "speech","lora_path": "/root/.cache/huggingface/hub/models--microsoft--Phi-4-multimodal-instruct/snapshots/6cf9696e152090d43282b3830adbb6cc8b2d0250/speech-lora" }'
```

Could there be some issue with reading from /root/?

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
