### ISSUE TITLE
[Bug]: Qwen/Qwen2.5-VL-3B-Instruct doesnt call tools

### ISSUE THREAD

**Issue by PedroMiolaSilva** [vllm-project/vllm#16797]
### Your current environment

ok

### 🐛 Describe the bug

I'm trying to use function calling with Qwen2.5-VL-3B-Instruct but it seems that the model doesnt have access to the tools.

Im using:

```
#!/bin/bash
source ../.env
export MODEL_ID=Qwen/Qwen2.5-VL-3B-Instruct
export MODEL_ID_PORT=8000
export MODEL_ID_GPU=0

docker run \
--ipc=host \
--runtime nvidia \
-e VLLM_USE_V1=1 \
-p "${MODEL_ID_PORT}:8000" \
--env "HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}" \
--env "CUDA_VISIBLE_DEVICES=${MODEL_ID_GPU}" \
--env "VLLM_ALLOW_RUNTIME_LORA_UPDATING=True" \
-v "VLLM_LOGGING_LEVEL=${VLLM_LOGGING_LEVEL}" \
-v "${HF_HOME}:/root/.cache/huggingface" \
vllm/vllm-openai:latest \
--model ${MODEL_ID} \
--max-model-len 10000 \
--enable_auto_tool_choice \
--tool_call_parser hermes \
--gpu-memory-utilization 0.35 \
--enforce-eager
```

A simple request example is:

`curl http://localhost:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "Qwen/Qwen2.5-VL-3B-Instruct-AWQ",
    "temperature": 0.0001,
    "n": 1,
    "stream": false,
    "tools": [
      {
        "type": "function",
        "function": {
          "name": "get_current_temperature",
          "description": "Get current temperature at a location.",
          "parameters": {
            "type": "object",
            "properties": {
              "location": {
                "type": "string",
                "description": "The location to get the temperature for, in the format City, State, Country."
              },
              "unit": {
                "type": "string",
                "enum": ["celsius", "fahrenheit"],
                "description": "The unit to return the temperature in. Defaults to celsius."
              }
            },
            "required": ["location"],
            "additionalProperties": false
          }
        }
      }
    ],
    "messages": [
      {
        "role": "user",
        "content": "which tools do you have?"
      }
    ]
  }'
`

There is no error raised, just the responses always saying that it does not have access to any tools.

I've tried many different approaches and is not working properly. 

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Are you using the tool calling chat template?

**Comment by PedroMiolaSilva** [comment]
@DarkLight1337 thanks, it worked.

**Comment by dentroai** [comment]
@PedroMiolaSilva which chat template did you use? 

I tried `--chat-template examples/tool_chat_template_hermes.jinja` as well as `--chat-templateQwen/Qwen2.5-VL-72B-Instruct-AWQ`. 

The issue is that I try using Qwen 2.5 VL with FlowiseAI, they got some Custom ChatOpenAI node that calls vLLM. 

Works fine for normal text generation, but not can't figure it out using tools.

**Comment by PedroMiolaSilva** [comment]
@dentroai https://github.com/vllm-project/vllm/blob/main/examples/tool_chat_template_hermes.jinja this one! What is happening there?

**Comment by dentroai** [comment]
Thank you!
I guess it has to do how Flowise expects the LLM to answer.

Now that I know which chat template you use, I'll try again calling vLLM directly, circumventing flowise. 

Great news, I'm sure this will save me a lot of time, thanks.

**Comment by dentroai** [comment]
@PedroMiolaSilva just wanted to say that I got Qwen 2.5 VL to work with the chat template that you shared! Thank you very much, without you I would have been stuck for much longer! 💙

For reference for other vllm users, this is my docker compose for vllm, where `VLLM_LLM_MODEL_NAME` is `Qwen/Qwen2.5-VL-72B-Instruct`:
```
vllm_llm:
    image: vllm/vllm-openai:latest
    container_name: vllm_llm
    ports:
      - "127.0.0.1:${VLLM_LLM_PORT:-8000}:8000"
    volumes:
      - hf_cache:/root/.cache/huggingface
      - ./vllm/tool_chat_template_hermes.jinja:/tool_chat_template_hermes.jinja
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - HF_HUB_ENABLE_HF_TRANSFER=${HF_HUB_ENABLE_HF_TRANSFER:-false}
      - CUDA_LAUNCH_BLOCKING=1
      - MODEL_ID=${VLLM_LLM_MODEL_NAME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command:
      - --model
      - ${VLLM_LLM_MODEL_NAME}
      - --max-model-len
      - ${VLLM_LLM_MAX_MODEL_LEN:-8192}
      - --gpu-memory-utilization
      - ${VLLM_LLM_GPU_MEM_UTIL:-0.9}
      - --served-model-name
      - ${VLLM_LLM_SERVED_MODEL_NAME:-vllm-llm-model}
      - --enforce-eager
      - --tensor-parallel-size
      - ${VLLM_TENSOR_PARALLEL_SIZE:-1}
      - --enable-auto-tool-choice
      - --tool-call-parser
      - hermes
      - --chat-template
      - /tool_chat_template_hermes.jinja
    ipc: host
    restart: always
    networks:
      - rag_network
```

**Comment by yudidi** [comment]
I set chat-template,but some times I get error 
```

qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:08 [hermes_tool_parser.py:148] json.decoder.JSONDecodeError: Extra data: line 3 column 1 (char 56)
qwen2-5-vl-72b-server  | (APIServer pid=1) INFO:     10.0.18.41:33622 - "POST /v1/chat/completions HTTP/1.1" 200 OK
qwen2-5-vl-72b-server  | (APIServer pid=1) INFO 08-28 20:53:10 [loggers.py:123] Engine 000: Avg prompt throughput: 37.9 tokens/s, Avg generation throughput: 2.1 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 55.4%
qwen2-5-vl-72b-server  | (APIServer pid=1) INFO:     127.0.0.1:33814 - "GET /health HTTP/1.1" 200 OK
qwen2-5-vl-72b-server  | (APIServer pid=1) WARNING 08-28 20:53:15 [protocol.py:81] The following fields were present in the request but ignored: {'enable_thinking', 'thinking'}
qwen2-5-vl-72b-server  | (APIServer pid=1) WARNING 08-28 20:53:15 [sampling_params.py:311] temperature 1e-06 is less than 0.01, which may cause numerical errors nan or inf in tensors. We have maxed it out to 0.01.
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148] Error in extracting tool call from response.
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148] Traceback (most recent call last):
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py", line 126, in extract_tool_calls
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148]     json.loads(match[0] if match[0] else match[1])
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148]   File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148]     return _default_decoder.decode(s)
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148]   File "/usr/lib/python3.12/json/decoder.py", line 341, in decode
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148]     raise JSONDecodeError("Extra data", s, end)
qwen2-5-vl-72b-server  | (APIServer pid=1) ERROR 08-28 20:53:16 [hermes_tool_parser.py:148] json.decoder.JSONDecodeError: Extra data: line 3 column 1 (char 56)
qwen2-5-vl-72b-server  | (APIServer pid=1) INFO:     10.0.18.41:33626 - "POST /v1/chat/completions HTTP/1.1" 200 OK

```

I use docker-compose.yaml

```
version: '3.8'  
  
services:  
  qwen2-5-vl-72b:  
    image: vllm/vllm-openai:latest  
    container_name: qwen2-5-vl-72b-server   
    environment:  
      - NVIDIA_VISIBLE_DEVICES=0,1,2,3  
      - CUDA_VISIBLE_DEVICES=0,1,2,3
      #- HF_HOME=/root/.cache/huggingface
    ports:  
      - "8000:8000"  
    volumes:  
      - /home/pz/Qwen2.5-VL-72B-Instruct:/models/Qwen2.5-VL-72B-Instruct  
      #- /home/pz/Qwen2.5-VL-72B-Instruct:/root/.cache/huggingface/hub/models--Qwen--Qwen2.5-VL-72B-Instruct/snapshots/main
      - /dev/shm:/dev/shm    
    ipc: host
    deploy:  
      resources:
        limits:
          memory: 800000m
        reservations:  
          devices:  
            - driver: nvidia
              count: 4  
              capabilities: [gpu]
    working_dir: /models
    restart: always
    command: >  
      --model Qwen2.5-VL-72B-Instruct
      --tensor-parallel-size 4  
      --dtype bfloat16  
      --gpu-memory-utilization 0.9
      --max-model-len 32768
      --max-num-seqs 128
      --swap-space 64
      --host 0.0.0.0
      --port 8000
      --enable-auto-tool-choice  
      --tool-call-parser hermes
      --chat-template /vllm-workspace/examples/tool_chat_template_hermes.jinja
    healthcheck:  
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s  
      timeout: 10s  
      retries: 3  
      start_period: 120s
      #--limit-mm-per-prompt '{"image":4}'
```
sometimes the model output bad tool call message, not write tool call format.
