### ISSUE TITLE
[Bug]: RuntimeError on RTX 5090: "no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by danhnc96** [vllm-project/vllm#16901]
### Describe the bug

When running 

[vLLM.log](https://github.com/user-attachments/files/19829093/vLLM.log)

 with a NVIDIA RTX 5090 GPU, I encountered the following error:

RuntimeError: CUDA error: no kernel image is available for execution on the device

From the logs, it seems that PyTorch does not support the compute capability of the RTX 5090 (sm_120):

### To Reproduce

1. Use RTX 5090 GPU
2. Install vLLM with Docker or system Python environment
3. Launch the vLLM OpenAI API server
4. Engine fails to start due to CUDA kernel compatibility issue

### Environment

- **GPU**: NVIDIA GeForce RTX 5090
- **CUDA Driver Version**: 12.8
- **CUDA Toolkit**: 12.8.93
- **NVIDIA Driver**: 570.124.06
- **PyTorch Version**: 2.x (installed via pip)
- **vLLM Version**: Latest (from PyPI)
- **Python Version**: 3.10
- **OS**: Ubuntu 22.04

### Additional Context

It seems that the RTX 5090 uses a new compute capability (`sm_120`), which is currently not supported in the stable PyTorch build I'm using.

Is there a recommended way to run vLLM with this GPU? Should I:

- Switch to a nightly PyTorch build that supports sm_120?
- Build PyTorch from source with `TORCH_CUDA_ARCH_LIST="12.0"`?
- Wait for official support from PyTorch?

Any guidance or workaround would be greatly appreciated. Thanks!

### How you are installing vllm

```sh
pip install -vvv vllm
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Patrick10203** [comment]
I have the exact same issue with the RTX 5090. I found no solution so far.

**Comment by bi1101** [comment]
You have to build the image yourself

here's the docker that you can try.

clone the vllm repo and place this docker compose right OUTSIDE the repo

```yml
vllm-Qwen3-30B-A3B-AWQ:
    container_name: vllm-Qwen3-30B-A3B-AWQ
    image: vllm-cu128
    build:
      dockerfile: docker/Dockerfile
      context: vllm
      args:
        max_jobs: 16
        RUN_WHEEL_CHECK: "false"
        TORCH_CUDA_ARCH_LIST: "7.0 7.5 8.0 8.6 8.9 9.0+PTX 12.0"
    command: [ "--model", "cognitivecomputations/Qwen3-30B-A3B-AWQ", "--trust-remote-code", "--enable-reasoning", "--reasoning-parser", "deepseek_r1"]
    ports:
      - "8000:8000"
    environment:
      - VLLM_USE_V1=1
      - VLLM_MAX_SIZE_MB=10240
      - VLLM_FLASH_ATTN_VERSION=2
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
      # - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    # runtime: nvidia
    volumes:
      - vllm_cache:/root/.cache
      - model_data:/models
    # ipc: host
    # privileged: true
    # restart: unless-stopped
```
