### ISSUE TITLE
[Bug]: SamplingParams() use_beam_search error

### ISSUE THREAD

**Issue by michellewheatleyxsite** [vllm-project/vllm#18231]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Your output of `python collect_env.py` here
```

I am using the following packages/versions:
fschat==0.2.36
vllm==0.8.5.post1
fastapi==0.115.12

</details>

### 🐛 Describe the bug

I am trying to recreate a docker network that I had created about a year ago. I used the following docker-compose setup:
```
services:
  # Create network of docker containers
  fastchat-controller:
    image: fastchat:latest
    ports:
      - '31001:31001'
    entrypoint: ['python3', '-m', 'fastchat.serve.controller', '--host', '0.0.0.0', '--port', '31001']

  fastchat-model-worker-mistral7b:
    # Create container for Mistral7B LLM
    image: fastchat:latest
    environment:
      HF_TOKEN: 'HF-TOKEN'
    ports:
      - '31002:31002'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    entrypoint: ['python3', '-m', 'fastchat.serve.vllm_worker', '--model-path', 'mistralai/Mistral-7B-v0.1', '--trust-remote-code', '--model-impl', 'transformers','--gpu-memory-utilization', '0.4', '--max-model-len', '16300', '--worker-address', 'http://fastchat-model-worker-mistral7b:31002', '--controller-address', 'http://fastchat-controller:31001', '--host', '0.0.0.0', '--port', '31002']

  fastchat-api-server:
    # Create API server container
    image: fastchat:latest
    ports:
      - '8080:8080'
    entrypoint: ['python3', '-m', 'fastchat.serve.openai_api_server', '--controller-address', 'http://fastchat-controller:31001', '--host', '0.0.0.0', '--port', '8080', '--api-keys', '<INSERT-API-HERE>']
```
The containers successfully build, but when I try to test the code, I get **TypeError: Unexpected keyword argument 'use_beam_search'**. I have looked at a bunch of open and closed issues, and it seems like there is a related issue on the Fastchat GitHub (https://github.com/lm-sys/FastChat/issues/3631)
Here is the code I am using to test my vLLM server that I created using a docker network (tried two different methods, both failed).
```
from langchain_openai import OpenAI

API_KEY = '<KEY>'
OPENAI_API_BASE = 'http://<url>:8080/v1'
MODEL = 'mistralai/Mistral-7B-v0.1'

local_llm = OpenAI(
    model=MODEL,
    api_key='EMPTY',
    base_url=OPENAI_API_BASE,
    temperature=0.1,
    top_p=0.1,
    max_tokens=512
)

response = local_llm.invoke('What is the capital of Spain?')
print(response)

from openai import OpenAI

client = OpenAI(
    api_key=API_KEY,
    base_url=OPENAI_API_BASE
)

chat_response = client.chat.completions.create(
    model="Mistral-7B-v0.1",
    messages=[
        {"role": "user", "content": "What is the capital of Spain?"},
    ],
    extra_body={
        "use_beam_search": False
    },
    temperature=0.1,
)
print(chat_response)
```

Here is the error I get:
fastchat-api-server-1              | 2025-05-15 23:11:06 | INFO | stdout | INFO:     10.5.2.2:58853 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     return await self.app(scope, receive, send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await super().__call__(scope, receive, send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     raise exc
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await self.app(scope, receive, _send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     raise exc
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await app(scope, receive, sender)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await route.handle(scope, receive, send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await self.app(scope, receive, send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     raise exc
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     await app(scope, receive, sender)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     response = await f(request)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |                ^^^^^^^^^^^^^^^^
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     raw_response = await run_endpoint_function(
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     return await dependant.call(**values)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/fastchat/serve/vllm_worker.py", line 217, in api_generate
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     output = await worker.generate(params)
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/fastchat/serve/vllm_worker.py", line 173, in generate
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     async for x in self.generate_stream(params):
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |   File "/app/venv/lib/python3.11/site-packages/fastchat/serve/vllm_worker.py", line 106, in generate_stream
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |     sampling_params = SamplingParams(
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr |                       ^^^^^^^^^^^^^^^
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:06 | ERROR | stderr | **TypeError: Unexpected keyword argument 'use_beam_search'**
fastchat-model-worker-mistral7b-1  | 2025-05-15 23:11:44 | INFO | model_worker | Send heart beat. Models: ['Mistral-7B-v0.1']. Semaphore: Semaphore(value=1023, locked=False). call_ct: 1. worker_id: d567d395.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
