### ISSUE TITLE
[Bug]: Mistrall Small 3.2 doesn't work with images

### ISSUE THREAD

**Issue by tomschelsen** [vllm-project/vllm#20025]
### Your current environment

vLLM 0.9.1 (Docker)

`mistralai/Mistral-Small-3.2-24B-Instruct-2506`

Using `mistralai/Mistral-Small-3.1-24B-Instruct-2503` with everything else unchanged works.

### 🐛 Describe the bug

`ERROR 06-24 14:40:09 [serving_chat.py:200] Error in preprocessing prompt inputs ERROR 06-24 14:40:09 [serving_chat.py:200] Traceback (most recent call last): ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/serving_chat.py", line 183, in create_chat_completion ERROR 06-24 14:40:09 [serving_chat.py:200] ) = await self._preprocess_chat( ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/serving_engine.py", line 787, in _preprocess_chat ERROR 06-24 14:40:09 [serving_chat.py:200] conversation, mm_data_future = parse_chat_messages_futures( ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/entrypoints/chat_utils.py", line 1196, in parse_chat_messages_futures ERROR 06-24 14:40:09 [serving_chat.py:200] sub_messages = _parse_chat_message_content( ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/entrypoints/chat_utils.py", line 1120, in _parse_chat_message_content ERROR 06-24 14:40:09 [serving_chat.py:200] result = _parse_chat_message_content_parts( ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/entrypoints/chat_utils.py", line 1020, in _parse_chat_message_content_parts ERROR 06-24 14:40:09 [serving_chat.py:200] parse_res = _parse_chat_message_content_part( ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/entrypoints/chat_utils.py", line 1077, in _parse_chat_message_content_part ERROR 06-24 14:40:09 [serving_chat.py:200] mm_parser.parse_image(str_content) ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/entrypoints/chat_utils.py", line 777, in parse_image ERROR 06-24 14:40:09 [serving_chat.py:200] placeholder = self._tracker.add("image", image_coro) ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/entrypoints/chat_utils.py", line 586, in add ERROR 06-24 14:40:09 [serving_chat.py:200] mm_processor = mm_registry.create_processor(model_config) ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/multimodal/registry.py", line 275, in create_processor ERROR 06-24 14:40:09 [serving_chat.py:200] model_cls = self._get_model_cls(model_config) ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/multimodal/registry.py", line 246, in _get_model_cls ERROR 06-24 14:40:09 [serving_chat.py:200] model_cls, _ = get_model_architecture(model_config) ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/utils.py", line 240, in get_model_architecture ERROR 06-24 14:40:09 [serving_chat.py:200] model_cls, arch = ModelRegistry.resolve_model_cls(architectures) ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/model_executor/models/registry.py", line 489, in resolve_model_cls ERROR 06-24 14:40:09 [serving_chat.py:200] return self._raise_for_unsupported(architectures) ERROR 06-24 14:40:09 [serving_chat.py:200] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ERROR 06-24 14:40:09 [serving_chat.py:200] File "/workspace/.venv/lib/python3.12/site-packages/vllm/model_executor/models/registry.py", line 426, in _raise_for_unsupported ERROR 06-24 14:40:09 [serving_chat.py:200] raise ValueError( ERROR 06-24 14:40:09 [serving_chat.py:200] ValueError: Model architectures ['PixtralForConditionalGeneration'] failed to be inspected. Please check the logs for more details. INFO: 10.231.0.4:36046 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request`

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by princepride** [comment]
@DarkLight1337 Can you assign this task to me, I noticed that the Mistral 3.2 seems different from Mistral 3.1, I reproduced the problem and noticed some code works on Mistral 3.1 but not works on Mistral 3.2, I will try to solve it.

**Comment by gaby** [comment]
@princepride Both `small-3.2` and `magistral` require the latest `mistral-common>=1.6.2` package.

While support for that was merged, there hasn't been any releases in 2 weeks, so when people use the latest docker image it's using an older package without the new mistral tokenizer.

**Comment by princepride** [comment]
I see, but when I change the model from mistral3.1 to mistral3.2 and run the example code of offline vision inference, got another error.

**Comment by gaby** [comment]
Interesting, I did notice I can't get function calling to work properly with small/devstral and vLLM. But it's related to vLLM using regex to perse JSON and not handling single quotes.

**Comment by princepride** [comment]
I know where the problem lies. Mistral has its own tokenizer function, and the online reasoning code follows their logic, but the offline reasoning in the example does not configure Mistral's own tokenizer function. Fortunately, Mistral 3.1 has a complete set of standard transformers format tokenizer configuration files, but Mistral 3.2 lacks it. This results in the same example code being able to run in Mistral 3.1, but not in Mistral 3.2. I have seen that many users have requested that the huggingface repository of Mistral 3.2 also provide a complete set of transformers configuration files. By the way, I think we should add `ignore_patterns=["consolidated.safetensors"]` in the example, because now all the weight files in the huggingface repository will be downloaded, which is close to 100G.

**Comment by DarkLight1337** [comment]
cc @patrickvonplaten

**Comment by erikmargaronis** [comment]
I stumbled upon this thread when trying out Mistral Small 3.2 with vLLM v0.9.1 but both vision and tool calling seem to work fine for me. For tool calling I had to specify the chat template suggested by vLLM here: [https://docs.vllm.ai/en/stable/features/tool_calling.html#mistral-models-mistral](https://docs.vllm.ai/en/stable/features/tool_calling.html#mistral-models-mistral)

 My compose file:


```
services:
  vllm-service:
    image: vllm/vllm-openai:v0.9.1
    networks:
      - common_network
    environment:
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
      - VLLM_FLASH_ATTN_VERSION=3
      - VLLM_USE_V1=0
    command:
      - "--host=0.0.0.0"
      - "--port=8000"
      - "--model=/app/Mistral-Small-3.2-24B-Instruct-2506"
      - "--served-model-name=Mistral-Small-3.2-24B-Instruct-2506"
      - "--enforce-eager"
      - "--max-model-len=65535"
      - "--tokenizer_mode=mistral"
      - "--load_format=mistral"
      - "--config_format=mistral"
      - "--dtype=half"
      - "--enable-auto-tool-choice"
      - "--tool-call-parser=mistral"
      - "--limit-mm-per-prompt"
      - "image=10"
      - "--chat-template=/templates/tool_chat_template_mistral_parallel.jinja"
    volumes:
      - "/model-share/mistralai/Mistral-Small-3.2-24B-Instruct-2506:/app/Mistral-Small-3.2-24B-Instruct-2506"
      - "/model-share/chat_templates/tool_chat_template_mistral_parallel.jinja:/templates/tool_chat_template_mistral_parallel.jinja"
    ports:
      - "5008:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ '0' ]

```
