### ISSUE TITLE
V0.2.4 Docker Image fails to run mixtral

### ISSUE THREAD

**Issue by jrsperry** [vllm-project/vllm#2052]
Using kubernetes, with the abbreviated configuration and version v0.2.4 of the docker image: 
```
      containers:
        - name: mixtral-vllm
          args:
            - "--model"
            - "mistralai/Mixtral-8x7B-Instruct-v0.1"
            - "--tensor-parallel-size"
            - "2"
            ...
```

I get a `KeyError: 'mixtral'` error.  V0.2.4 should support mixtral, is there additional config required?
