### ISSUE TITLE
Unable to specify GPU usage in VLLM code

### ISSUE THREAD

**Issue by humza-sami** [vllm-project/vllm#3012]
I am facing difficulties in specifying GPU usage for different models for LLM inference pipeline using vLLM. Specifically, I have 4 RTX 4090 GPUs available, and I aim to run a LLM with a size of 42GB on 2 RTX 4090 GPUs (~48GB) and a separate model with a size of 22GB on 1 RTX 4090 GPU(`24GB).
This is my code for running 42GB model on two GPUs.
```python
from vllm import LLM
llm = LLM(model_name, max_model_len=50, tensor_parallel_size=2)
output = llm.generate(text)
```

However, I haven't found a straightforward method within the VLLM library to specify which GPU should be used for each model.

**Comment by simon-mo** [comment]
You can specify the devices by using `CUDA_VISIBLE_DEVICES` environment variable.

**Comment by humza-sami** [comment]
> You can specify the devices by using `CUDA_VISIBLE_DEVICES` environment variable.

@simon-mo 

```python
from vllm import LLM
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1,2"
llm_1 = LLM(llm_1_name,max_model_len=50,gpu_memory_utilization=0.9, tensor_parallel_size=2)

os.environ["CUDA_VISIBLE_DEVICES"] = "3"
llm_2 = LLM(llm_2_name,max_model_len=50,gpu_memory_utilization=0.9, tensor_parallel_size=1)
```
this still loads 2nd llm on 1 and 2 gpu and gives memory error

**Comment by simon-mo** [comment]
Try instantiate them in different script?

**Comment by humza-sami** [comment]
@simon-mo Separatly they work but my goal is to run two different LLMs. One LLM on 2 GPUs and Second LLM on 3rd GPU

**Comment by KatIsCoding** [comment]
I've had your exact same scenario, my solution was to run on docker-compose, because in there you can specify which GPU ids to make available to each instance

**Comment by KatIsCoding** [comment]
And then expose their APIs and consume with another script, it would be faster if you run the openai compatible API, however if you want to add something custom like `lmformatenforcer`, you might need to make the implementation yourself

**Comment by humza-sami** [comment]
@KatIsCoding Thanks for your suggestion. Yeah I endedup with same thought that I have to implement the ray clustering by myself. What I have noticed is that when I initialized 2nd LLM object then it recreate a cluster of GPU/CPU. If I manually change `CUDA_VISIBLE_DEVICES` before making 2nd LLM object in same python script then ray confuses and throw error because current configuration clash with 1st LLM object cluster.
In single process (script), you cannot make 2nd LLM object by changing `CUDA_VISIBLE_DEVICES`.

**Comment by humza-sami** [comment]
@KatIsCoding can you share docker setup? I haven't have much experiance with docker. Thanks

**Comment by Xiwang-Li-Walmart** [comment]
Any progress here?

**Comment by sAviOr287** [comment]
@humza-sami were you able to figure out how to do this? I am facing the same problem and have no idea how to fix it atm. There is a solution using RAY but not sure how to implement that
Do you have any news on this issue?

**Comment by KatIsCoding** [comment]
> @KatIsCoding can you share docker setup? I haven't have much experiance with docker. Thanks



> @humza-sami were you able to figure out how to do this? I am facing the same problem and have no idea how to fix it atm. There is a solution using RAY but not sure how to implement that Do you have any news on this issue?

I'm sorry for my late response on the topic, as @sAviOr287 mentioned, there is a ray implementation out there, however I could not find much information about it.

So far my approach to the problem was just using docker and different instances for different models, like so:

```yml
version: "3.8"

networks:
  load_balancing:
    name: load_balancing

services:
  sqlcoder:
    profiles: [ai]
    image: aiimage
    shm_size: "15gb"
    command: python3 ./aiplug.service.py
    hostname: sqlcoder
    networks:
      - load_balancing
    environment:
      - MODEL_ID=defog/sqlcoder-7b-2
      - TP_SIZE=1
      - ACCEPT_EMPTY_IDS=1
    build:
      context: .
      dockerfile: ./apps/VLLM/ai-service.Dockerfile
    volumes:
      - ./apps/VLLM/:/app:ro
      - ./models:/aishared
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]

  llama:
    profiles: [ai-exp]
    image: aiimage
    shm_size: "15gb"
    command: python3 ./aiplug.service.py
    hostname: llama
    networks:
      - load_balancing
    environment:
      - AI_SERVICE_PORT=1337
      - MODEL_ID=meta-llama/Meta-Llama-3-8B-Instruct
      - ACCEPT_EMPTY_IDS=1
      - TP_SIZE=1
    build:
      context: .
      dockerfile: ./apps/VLLM/ai-service.Dockerfile
    volumes:
      - ./apps/VLLM/:/app:ro
      - ./models:/aishared
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
  nginx:
    image: nginx:1.15-alpine
    profiles: [ai]
    networks:
      - load_balancing
    depends_on:
      - sqlcoder
      - llama
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - 6565:6565 #SQL Coder
      - 6566:6566 #Llama
```

It is a load balancing approach, however a different model gets hit depending on which port you are using.
My dockerfile is pretty much just installing vllm + some other stuff, however it could be completely replaced with something like the OpenAI implementation vllm has.

**Comment by KatIsCoding** [comment]
The most important thing about the configuration is the usage of
```yml
deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
```

By specifying a `device_ids` you are essentially telling docker which GPUs to make available in each process
