### ISSUE TITLE
Docker deployment with mistralai/Mistral-7B-v0.1 model

### ISSUE THREAD

**Issue by BBjie** [vllm-project/vllm#3435]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I'm trying to use docker to deploy vllm in EC2 instance
here is my docker-compose.yaml looks like
```
services:
  vllm:
    image: vllm/vllm-openai:latest
    command: --model mistralai/Mistral-7B-v0.1
    environment:
      - HUGGING_FACE_HUB_TOKEN="key"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
When I was trying to run it, it always returned an error that said
` vllm-1  | ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (16832). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.`

what should  I change to make it run with my compose file? It seems like there is no env variables like gpu_memory_utilization
and max_model_len that I can pass value in
