### ISSUE TITLE
[Bug]: Llama 3.1 405 B  FP16 model failed to load on AMD GPU 

### ISSUE THREAD

**Issue by jerin-scalers-ai** [vllm-project/vllm#7032]
### Your current environment

vLLM version: 0.5.3.post1 (For ROCm)
Model: meta-llama/Meta-Llama-3.1-405B-Instruct
8 x AMD MI300x GPU

### 🐛 Describe the bug

```
services:
  vllm-serving:
    container_name: vllm-serving
    image: vllm-rocm:v0.5.3.post1
    environment:
      - LLM_MODEL=$LLM_MODEL
      - HUGGING_FACE_HUB_TOKEN=$HF_TOKEN
    command: >
      sh -c "
      python3 -m vllm.entrypoints.openai.api_server \
      --model $LLM_MODEL --dtype float16 \
      --tensor-parallel-size 8
      "
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    volumes:
      - /mnt/model/:/models/
    shm_size: 16G
    ports:
      - 8000:8000
```

[rank0]: huggingface_hub.utils._errors.HfHubHTTPError: 416 Client Error: Requested Range Not Satisfiable for url: https://cdn-lfs-us- .....
ERROR 08-01 07:45:19 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 76 died, exit code: -15
INFO 08-01 07:45:19 multiproc_worker_utils.py:123] Killing local vLLM worker processes
/opt/conda/envs/py_3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

![Screenshot 2024-08-01 152943](https://github.com/user-attachments/assets/4bc5a412-54e1-448a-90d5-1cb45147e576)
