### ISSUE TITLE
[RFC]: Add a FastChat like routing server to provide a central endpoint for multiple models

### ISSUE THREAD

**Issue by fozziethebeat** [vllm-project/vllm#7480]
### Motivation.

FastChat has a Controller -> multiple worker setup whereby individual worker nodes run a single model and report their model list to a master controller that handles routing.  This allows some users to setup multiple models and connect them to a unified router server that receives incoming traffic and portions it out to the right worker.  

This would solve one of the [FAQ items](https://docs.vllm.ai/en/latest/serving/faq.html).

### Proposed Change.

For the OpenAI compatible server:
* Add a heartbeat registration step to the openai entrypoint that registers the server's model to a `routing` server. 
* Create a new `routing` server that acts as both controller and OpenAI shim.  It receives the initial user requests and forwards the request to an actual vLLM server as a pass through.  It also receives the registration calls from actual vLLM servers to populate the list of supported models. 

### Feedback Period.

one week

**Comment by fozziethebeat** [comment]
Additional Notes: we already did this with a private repo we can't totally share but I extracted the core part and put the router server changes in this draft branch: https://github.com/fozziethebeat/vllm/blob/routing_server/vllm/entrypoints/openai/routing_server.py

**Comment by youkaichao** [comment]
I think there is already a community library that does this: https://docs.litellm.ai/docs/simple_proxy#load-balancing---multiple-instances-of-1-model

**Comment by fozziethebeat** [comment]
oh wow, I didn't realize that was something you could run locally with a config file.  Let me test that and then re-asses this RFC

**Comment by fozziethebeat** [comment]
Okay, dropping this RFC.  Its easy enough to do this with litellm.

I'll note for anyone doing this, litellm's docs are wrong in subtle and frustrating ways.  A simple config for this setup is something like the following:


```
model_list:
  - model_name: allenai/wildguard
    litellm_params:
      model: openai/allenai/wildguard
      api_base: http://0.0.0.0:8001/v1
      api_key: nonce 
- model_name: allenai/wildguard-better 
    litellm_params:
      model: openai/allenai/wildguard
      api_base: http://0.0.0.0:8001/v1
      api_key: nonce
```
