### ISSUE TITLE
[Bug]: SpeculativeDecoding is outputting nonsense words

### ISSUE THREAD

**Issue by kerthcet** [vllm-project/vllm#8071]
### Your current environment

I deployed the vllm in cloud, with image: `vllm/vllm-openai:v0.5.1` and the commands:
```
  containers:
  - args:
    - --model
    - /workspace/models/models--facebook--opt-6.7b
    - --speculative_model
    - /workspace/models/models--facebook--opt-125m
    - --served-model-name
    - opt-6--7b
    - --host
    - 0.0.0.0
    - --port
    - "8080"
    - -tp
    - "1"
    - --use-v2-block-manager
    - --num_speculative_tokens
    - "5"
    command:
    - python3
    - -m
    - vllm.entrypoints.openai.api_server
```

### 🐛 Describe the bug

I asked the question:

```
curl http://localhost:8080/v1/completions \
-H "Content-Type: application/json" \
-d '{
    "model": "opt-6--7b",
    "prompt": "The future of AI is",
    "max_tokens": 10,
    "temperature": 0.7
}'
```

The output:
```
DungeonCanadaci UCH TRANS fingers Professional Adin pee Swansea
```

The words is nonsense. If I changed to temperature to 0, the output is:

```
<s><s><s><s><s><s><s><s><s><s>
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
