### ISSUE TITLE
Container environment: The fschat package is installed, but when i  run the code, still prompted that fschat is not installed

### ISSUE THREAD

**Issue by Zhang-star-master** [vllm-project/vllm#839]
<img width="961" alt="1692775963281" src="https://github.com/vllm-project/vllm/assets/25812074/f01fbad5-f5bd-46aa-8f1d-2c796d5d1786">

**Comment by wenpengwu** [comment]
You can try installing the latest fastchat through the source code 
```code
git clone https://github.com/lm-sys/FastChat.git
cd FastChat
pip3 install -e .
```

**Comment by misterkuka** [comment]
Same issue here, fschat is installed yet when I run the code I get the error :(

**Comment by fredespi** [comment]
It looks like downgrading fschat to 0.2.23 like so:
`pip install fschat==0.2.23`
 helps but then there is another problem which is that the request comes in but it never returns anything and after a long time there is this in the log:
`INFO 08-23 20:55:40 async_llm_engine.py:196] Aborted request cmpl-4e09c99643aa452eb2650485f8335983.`

**Comment by fredespi** [comment]
I have found, after getting the idea from another issue, that installing fschat like so works:
`pip install "fschat[model_worker,webui]"`
And the problem I had above, where everything seemed to work but the model didn't return anything, was solved by running multiple gpus. But this required yet some more tweaking like in the StatefulSet yaml file ([reference](https://stackoverflow.com/questions/43373463/how-to-increase-shm-size-of-a-kubernetes-container-shm-size-equivalent-of-doc)):
```
          volumeMounts:
            - name: vllm-storage # to save models
              mountPath: /models
            - mountPath: /dev/shm # like docker's --shm-size=
              name: dshm
```
and 
 ```
     volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 10.24Gi
```
So finally I succeeded in running 2 T4 gpus on one kubernetes node, with the openai server, like so:
`python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --model $MODEL_NAME --swap-space 1 --tensor-parallel-size 2 --tokenizer 'hf-internal-testing/llama-tokenizer'`

Here are my relevant versions:
fschat                   0.2.24
vllm                     0.1.3
torch                    2.0.1
typing_extensions        4.5.0
pydantic                 1.10.0
