### ISSUE TITLE
[RFC]: Adopt mergify for auto-labeling PRs

### ISSUE THREAD

**Issue by russellb** [vllm-project/vllm#9192]
### Motivation.

vLLM is a very active project with a large and busy queue of PRs. Additional usage of github labels would assist with narrowing down which PRs to look at given a person's interests, as well as the state of the PR.

### Proposed Change.

Adopt mergify to perform automated labeling of PRs. https://docs.mergify.com/

While github also provides an [action for PR labeling](https://github.com/actions/labeler), it only supports labeling based on the branch and the files changed. Mergify supports labeling based on more criteria, such as whether a branch has conflicts with `main`.

Configuration would go into `.github/mergify.yml`. An example entry to auto-label PRs that touch files in the `docs/` directory:

```yaml
- name: label-documentation
  description: Automatically apply documentation label
  conditions:
    - or:
      - files~=^[^/]+\.md$
      - files~=^CONTRIBUTING/
      - files~=^docs/
  actions:
    label:
      add:
        - documentation
```

Here is an example that is a bit more unique to Mergify's capabilities. This sample configuration will label a PR and comment tagging the PR author if the PR goes into conflict with the target branch (`main`). It will also automatically remove the label once conflicts are resolved.

```yaml
- name: ping author on conflicts and add 'needs-rebase' label
  conditions:
      - conflict
      - -closed
  actions:
    label:
      add:
        - needs-rebase
    comment:
      message: |
       This pull request has merge conflicts that must be resolved before it can be
       merged. @{{author}} please rebase it. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

- name: remove 'needs-rebase' label when conflict is resolved
  conditions:
      - -conflict
      - -closed
  actions:
    label:
      remove:
        - needs-rebase
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
