### ISSUE TITLE
[Bug]: 500 Internal Server Error when calling v1/completions and v1/chat/completions with vllm/vllm-openai:v0.6.2 on K8s

### ISSUE THREAD

**Issue by apexx77** [vllm-project/vllm#9193]
### Your current environment
<details>
<summary>The output of `python collect_env.py`</summary>

```text
$ python3 collect_env.py
Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.12.6 (main, Sep 10 2024, 00:05:17) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.14.0-427.28.1.el9_4.x86_64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA L40S
Nvidia driver version: 550.90.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 57 bits virtual
CPU(s):                             128
On-line CPU(s) list:                0-127
Thread(s) per core:                 2
Core(s) per socket:                 32
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              143
Model name:                         Intel(R) Xeon(R) Gold 6448Y
Stepping:                           8
CPU MHz:                            4100.000
CPU max MHz:                        4100.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4200.00
Virtualization:                     VT-x
L1d cache:                          3 MiB
L1i cache:                          2 MiB
L2 cache:                           128 MiB
L3 cache:                           120 MiB
NUMA node0 CPU(s):                  0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,118,120,122,124,126
NUMA node1 CPU(s):                  1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced / Automatic IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hfi vnmi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr ibt amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flashinfer==0.1.6+cu121torch2.4
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.68
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.45.0
[pip3] triton==3.0.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.1.dev238+ge2c6e0a82
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0,2,4,6,8,10    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
$ 
```
</details>

### 🐛 Describe the bug

Getting "500 Internal Server Error" while calling `v1/completions` and `v1/chat/completions` endpoints when deployed on Kubernetes. Remaining endpoints sych as `tokenize` and `v1/models` are working as expected. Followed the deployment guide provided [here](https://github.com/vllm-project/vllm/blob/main/docs/source/serving/deploying_with_k8s.rst). 

```
INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
DEBUG 10-09 05:19:37 client.py:148] Heartbeat successful.
INFO:     10.121.X.X:33112 - "GET /health HTTP/1.1" 200 OK
INFO:     10.121.X.X:33122 - "GET /v1/models HTTP/1.1" 200 OK
INFO 10-09 05:19:37 logger.py:36] Received request tokn-788eaaca463f4228a9458b94a97bb373: prompt: 'Sample sentence for API testing', params: None, prompt_token_ids: None, lora_request: None, prompt_adapter_request: None.
INFO:     10.121.X.X:33124 - "POST /tokenize HTTP/1.1" 200 OK
INFO:     10.121.X.X:33134 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     10.121.X.X:33142 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
DEBUG 10-09 05:19:39 client.py:148] Heartbeat successful.
DEBUG 10-09 05:19:41 client.py:148] Heartbeat successful.
DEBUG 10-09 05:19:43 client.py:148] Heartbeat successful.
DEBUG 10-09 05:19:44 client.py:164] Waiting for output from MQLLMEngine.
DEBUG 10-09 05:19:45 client.py:148] Heartbeat successful.
DEBUG 10-09 05:19:45 engine.py:212] Waiting for new requests in engine loop.
DEBUG 10-09 05:19:47 client.py:148] Heartbeat successful.
```
Here is the yml used to create the deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vllm-app
  name: vllm-deployment
  namespace: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-app
  template:
    metadata:
      labels:
        app: vllm-app
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args: ["vllm serve neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8 --trust-remote-code --enable-chunked-prefill --max-model-len 16384 --disable-log-stats"]
        image: vllm/vllm-openai:v0.6.2
        env:
        - name: HF_HOME
          value: /home/.cache/huggingface
        - name: VLLM_CONFIG_ROOT
          value: /home/.cache/vllm
        - name: VLLM_CACHE_ROOT
          value: /home/.cache/vllm
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
        - name: VLLM_TRACE_FUNCTION
          value: "1"
        imagePullPolicy: Always
        name: vllm-openai
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 2
            memory: 20Gi
          requests:
            nvidia.com/gpu: 1
            cpu: 2
            memory: 20Gi
        volumeMounts:
        - mountPath: /home/.cache/
          name: cache-volume
        - mountPath: /dev/shm
          name: shm
      volumes:
      - name: cache-volume 
        persistentVolumeClaim:
          claimName: llama3-1-8b
      - name: shm
        emptyDir: 
          medium: Memory
          sizeLimit: "4Gi"
```

There is no detailed trace for the error even after setting `VLLM_LOGGING_LEVEL` and `VLLM_TRACE_FUNCTION` env variables.

Do we need to change any configuration to get it working as expected?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
