### ISSUE TITLE
Deployment stuck when using kuberay to scale Multi-GPU LLM on Kubernetes

### ISSUE THREAD

**Issue by Hido1994** [vllm-project/vllm#973]
I want to use kuberay to serve and horizontaly-scale my LLM on Kubernetes.

The python code i want to deploy looks somewhat like this:
```
import json
import logging
from typing import AsyncGenerator

import ray
from fastapi import BackgroundTasks
from huggingface_hub import login
from ray import serve
from starlette.requests import Request
from starlette.responses import StreamingResponse, Response
from vllm.engine.arg_utils import AsyncEngineArgs
from vllm.engine.async_llm_engine import AsyncLLMEngine
from vllm.sampling_params import SamplingParams
from vllm.utils import random_uuid

logger = logging.getLogger("ray.serve")
@serve.deployment()
class VLLMPredictDeployment:
    def __init__(self, **kwargs):
        """
        Construct a VLLM deployment.

        Refer to https://github.com/vllm-project/vllm/blob/main/vllm/engine/arg_utils.py
        for the full list of arguments.

        Args:
            model: name or path of the huggingface model to use
            download_dir: directory to download and load the weights,
                default to the default cache dir of huggingface.
            use_np_weights: save a numpy copy of model weights for
                faster loading. This can increase the disk usage by up to 2x.
            use_dummy_weights: use dummy values for model weights.
            dtype: data type for model weights and activations.
                The "auto" option will use FP16 precision
                for FP32 and FP16 models, and BF16 precision.
                for BF16 models.
            seed: random seed.
            worker_use_ray: use Ray for distributed serving, will be
                automatically set when using more than 1 GPU
            pipeline_parallel_size: number of pipeline stages.
            tensor_parallel_size: number of tensor parallel replicas.
            block_size: token block size.
            swap_space: CPU swap space size (GiB) per GPU.
            gpu_memory_utilization: the percentage of GPU memory to be used for
                the model executor
            max_num_batched_tokens: maximum number of batched tokens per iteration
            max_num_seqs: maximum number of sequences per iteration.
            disable_log_stats: disable logging statistics.
            engine_use_ray: use Ray to start the LLM engine in a separate
                process as the server process.
            disable_log_requests: disable logging requests.
        """
        login(token='[HF_TOKEN]')
        kwargs = {**kwargs, 'tensor_parallel_size': 2, 'model': 'meta-llama/Llama-2-7b-chat-hf'}
        args = AsyncEngineArgs(**kwargs)
        self.engine = AsyncLLMEngine.from_engine_args(args)

    async def stream_results(self, results_generator) -> AsyncGenerator[bytes, None]:
        num_returned = 0
        async for request_output in results_generator:
            text_outputs = [output.text for output in request_output.outputs]
            assert len(text_outputs) == 1
            text_output = text_outputs[0][num_returned:]
            ret = {"text": text_output}
            yield (json.dumps(ret) + "\n").encode("utf-8")
            num_returned += len(text_output)

    async def may_abort_request(self, request_id) -> None:
        await self.engine.abort(request_id)

    async def __call__(self, request: Request) -> Response:
        """Generate completion for the request.

        The request should be a JSON object with the following fields:
        - prompt: the prompt to use for the generation.
        - stream: whether to stream the results or not.
        - other fields: the sampling parameters (See `SamplingParams` for details).
        """
        request_dict = await request.json()
        prompt = request_dict.pop("prompt")
        stream = request_dict.pop("stream", False)
        sampling_params = SamplingParams(**request_dict)
        request_id = random_uuid()
        results_generator = self.engine.generate(prompt, sampling_params, request_id)
        if stream:
            background_tasks = BackgroundTasks()
            # Using background_taks to abort the the request
            # if the client disconnects.
            background_tasks.add_task(self.may_abort_request, request_id)
            return StreamingResponse(
                self.stream_results(results_generator), background=background_tasks
            )

        # Non-streaming case
        final_output = None
        async for request_output in results_generator:
            if await request.is_disconnected():
                # Abort the request if the client disconnects.
                await self.engine.abort(request_id)
                return Response(status_code=499)
            final_output = request_output

        assert final_output is not None
        prompt = final_output.prompt
        text_outputs = [prompt + output.text for output in final_output.outputs]
        ret = {"text": text_outputs}
        return Response(content=json.dumps(ret))


deployment = VLLMPredictDeployment.bind()
```

The kubernetes configuration looks like this:
```
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: llm-manager
spec:
  serviceUnhealthySecondThreshold: 3600
  deploymentUnhealthySecondThreshold: 3600
  serveConfigV2: |
    applications:
    - name: model
      route_prefix: /
      import_path: model.ray.deployment_vllm_test:deployment
      runtime_env:
        working_dir: "[DIRECTORY_TO_PYTHON_CODE]"
      deployments:
      - name: VLLMPredictDeployment
        autoscaling_config:
          min_replicas: 1
          max_replicas: 1
          target_num_ongoing_requests_per_replica: 3
          downscale_delay_s: 3600
        ray_actor_options:
          num_gpus: 2
  rayClusterConfig:
    rayVersion: '2.6.2'
    enableInTreeAutoscaling: true
    autoscalerOptions:
      upscalingMode: Default
      idleTimeoutSeconds: 60
    headGroupSpec:
      serviceType: LoadBalancer # change to LoadBalancer for external access
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          imagePullSecrets:
            - name: docker-secret
          containers:
            - name: ray-head
              image: cortecs.ai/ray-worker:0.0.3
              resources:
                limits:
                  cpu: 1
                  memory: 8Gi
                requests:
                  cpu: 1
                  memory: 8Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 1
        groupName: llm-group
        rayStartParams: { }
        template:
          spec:
            nodeSelector:
              cloud.google.com/gke-nodepool: gpu-pool
            imagePullSecrets:
              - name: docker-secret
            containers:
              - name: ray-worker
                image: cortecs.ai/ray-worker:0.0.3
                lifecycle:
                  preStop:
                    exec:
                      command: [ "/bin/sh","-c","ray stop" ]
                resources:
                  limits:
                    cpu: 2
                    memory: 32Gi
                    nvidia.com/gpu: 2
                  requests:
                    cpu: 2
                    memory: 32Gi
                    nvidia.com/gpu: 2
            tolerations:
              - key: "ray.io/node-type"
                operator: "Equal"
                value: "worker"
                effect: "NoSchedule"
    headServiceAnnotations: { }
```

When I am using `tensor_parallel_size=1` and therefore deploy the LLM on a single GPU everything works as expected. 
But in the momement I use `tensor_parallel_size=2` or something higher the deployment get stuck and hangs forever with the following message `Deployment model_VLLMPredictDeployment has 1 replicas that have taken more than 30s to initialize. This may be caused by a slow __init__ or reconfigure method.`
After checking all of the logs in the ray dashboard the only thing I found which could be the issue is the following:
```
Using address llm-manager-raycluster-bpfjf-head-svc.ray-system.svc.cluster.local:6379 set in the environment variable RAY_ADDRESS
Connecting to existing Ray cluster at address: llm-manager-raycluster-bpfjf-head-svc.ray-system.svc.cluster.local:6379...
Calling ray.init() again after it has already been called.
```

I am using vllm version 0.1.4 and want to deploy this on Google Kubernetes Engine.
Any ideas whats the problem here?
